### ISSUE TITLE
Make SCL files work and autoboot

### ISSUE THREAD

**Issue by ghost** [bog-dan-ro/spectacol#25]
I tried booting SCL files but it sent me to the TRDOS prompt. I manually LISTed the contents and loaded the bootable file (LOAD"filename") but it just said DISK ERROR.

SCL files and possibly other Russian clones dont work properly.

When you finally get them working can you make them autoboot (like Unreal Speccy Portable does). Thanks.

**Comment by bog-dan-ro** [comment]
I think USP is using some kind of special ROM which does the magic. I'll check with FUSE folks to see what we can do.

**Comment by bog-dan-ro** [comment]
Upstreamed the problem here https://sourceforge.net/p/fuse-emulator/bugs/331/

**Comment by ghost** [comment]
Hi, did you manage to get these SCL files to work and autoboot ? Is there a projected release date for the new version ?

**Comment by bog-dan-ro** [comment]
The disk error was fixed by upstream https://sourceforge.net/p/fuse-emulator/code/5382/ and I'd like to wait a while for FUSE folks  to check https://sourceforge.net/p/fuse-emulator/feature-requests/90/ , then I'll release a new 1.x with this fix included.

**Comment by bog-dan-ro** [comment]
I cherry picked the upstream patch, and I published it beta channel, if you want to test it please use https://play.google.com/apps/testing/eu.licentia.games.spectacol to become a beta tester, wait a few hours until google play will make the change visible to everyone.

**Comment by ghost** [comment]
I joined the beta version about a week ago (and the program updated last night) but SCL files still don't boot. Even when I manually try to LOAD"filename" it says 'Disk Error'. (I know the filenames are case sensitive).

**Comment by reybits** [comment]
Same error 'Disk Error' on any SCL disc image.

**Comment by bog-dan-ro** [comment]
It seems you need to manually disable kempston interface from options.
I'll see what I can do to do it automatically

**Comment by reybits** [comment]
I have disabled Kempston mouse and Kempston joystick but it doesn't help - 'Disk Error'.

**Comment by bog-dan-ro** [comment]
I can reproduce it myself, it seems I need to update FUSE engine tonight and publish a new beta soon

**Comment by bog-dan-ro** [comment]
Published a new version which fixes it, it will take a few hours until will be visible everywhere.
For autoboot we need to wait for FUSE folks to implement it. An easier way to load it is to manually choose a pentagon 512|1024 and press enter twice.

**Comment by bog-dan-ro** [comment]
Disk error problem fixed in 1.2, hopefully autoboot will be fixed in 2.0

**Comment by bog-dan-ro** [comment]
@windale @andreyugolnik Thanks a lot folks for you support and patience ;-).

**Comment by ghost** [comment]
I didn't know about just pressing Enter twice to load SCL files, but you have to select the file first which takes you to a command prompt, then have to reset the machine and then press Enter twice. It's still faster than manually typing and loading the filename though, thanks. Patiently waiting for autoboot.

Scorpion ZS should be able to autoboot SCL files too (Spectaculator does, and I think it might be more compatible than Pentagon). I hope the FUSE team also add autoboot for Scorpion (or if you could let them know).

**Comment by ghost** [comment]
What just updated because autoboot still doesn't work ?
